### ISSUE TITLE
Issues writing epsilon to calculator.

### ISSUE THREAD

**Issue by Increedible** [eclipse/epsilon#61] opened 2023-10-27 09:30 UTC
I have been trying to write an up-to-date clone if this repo to my machine on wsl, and I got it to run on simulation. Following the tutorial at https://www.numworks.com/resources/engineering/software/build/ I gave up on wsys2 with too much errors, but now on linux I got it running with `make PLATFORM=simulator epsilon_run`. The issue rn is when I try to write to my calculator like the article says with `python3 build/device/dfu.py -s 0x90010000:leave -D output/release/device/n0110/userland/userland.A.dfu`, it says I'm missing the dfu which is obvious, so I tried to build it with `make userland.A.dfu`, but that gave me the error of:
`make userland.A.dfu
QSTRDAT python/port/genhdr/qstrdefs.generated.h
HOSTCC  kandinsky/fonts/rasterizer
RASTER  kandinsky/fonts/SmallFont.cpp
RASTER  kandinsky/fonts/LargeFont.cpp
HOSTCC  escher/image/inliner
APPSLYT apps/home/apps_layout.h
I18N    apps/i18n.h
CXX     apps/apps_container.o
CXX     apps/apps_container_helper.o
CXX     apps/apps_container_launch_default.o
CXX     apps/apps_container_prompt_none.o
apps/apps_container_prompt_none.cpp: In static member function 'static void AppsContainer::__static_initialization_and_destruction_0(int, int)':
apps/apps_container_prompt_none.cpp:5:15: warning: statement has no effect [-Wunused-value]
    5 | const KDColor AppsContainer::k_promptColors[] = {};
      |               ^~~~~~~~~~~~~
CXX     apps/apps_container_storage.o
CXX     apps/apps_window.o
...
CC      python/src/py/unicode.o
CC      python/src/py/vm.o
CC      python/src/py/vstr.o
CC      python/src/py/warning.o
LD      userland.A.elf
arm-none-eabi-gcc: error: ASSERTIONS=0: No such file or directory
make: *** [build/rules.mk:83: output/release/device/n0110/userland/userland.A.elf] Error 1
` the file is just plainly missing, and I have no idea what to do after googeling away.

**Comment by agarciadom** [comment] 2023-10-28 17:13
Sorry, but it looks you may have filed this issue to the wrong repository. Were you thinking about this project, perhaps?

https://github.com/numworks/epsilon

Closing as the issue is unrelated to this repository.

**Closed by agarciadom** 2023-10-28 17:13 UTC
