### ISSUE TITLE
Add support for varargs

### ISSUE THREAD

**Issue by kolovos** [eclipse/epsilon#1] opened 2022-10-20 08:50 UTC
As reported in [this forum post](https://www.eclipse.org/forums/index.php/t/1111822/), the following code fails as `Files.copy(...)` defines a varargs parameter, and `ReflectionUtil.searchMethodsFor(...)` doesn't support varargs.

```
var a = new Native("java.io.File")("a").toPath();
var b = new Native("java.io.File")("b").toPath();
var Files = Native("java.nio.file.Files");
Files.copy(a,b);
```

The error message produced in such cases is quite confusing:

```
Invalid number (or types) of arguments for operation 'copy': expected 'java.nio.file.Path, java.nio.file.Path, java.nio.file.CopyOption[]' but got 'org.eclipse.epsilon.eol.dom.NameExpression, org.eclipse.epsilon.eol.dom.NameExpression'
	at (/Users/dk135/Dev/Eclipse/eclipse-2020-06/runtime-EclipseXtext/native-test/native-test.eol@4:0-4:16)
	at (/Users/dk135/Dev/Eclipse/eclipse-2020-06/runtime-EclipseXtext/native-test/native-test.eol@4:0-4:16)
	at (/Users/dk135/Dev/Eclipse/eclipse-2020-06/runtime-EclipseXtext/native-test/native-test.eol@1:0-4:16)
	at (/Users/dk135/Dev/Eclipse/eclipse-2020-06/runtime-EclipseXtext/native-test/native-test.eol@1:0-4:16)
```

This is because, if everything else fails, we end up in `DynamicOperation.execute(...)`, while we shouldn't in this case. 

Copying @SMadani as the original developer of `DynamicOperation`.

**Comment by jgsuess** [comment] 2022-10-21 04:28
Please consider reusing [`Statement.execute()`](https://docs.oracle.com/javase/7/docs/api/java/beans/Statement.html#execute()), as its
> implementation should choose the most specific method using the algorithm specified in the Java Language Specification (15.11)

which is probably the intended behaviour.

**Comment by SMadani** [comment] 2022-10-23 12:41
This should now be fixed in the latest interim version. Feel free to reopen this issue if you spot any cases where it doesn't work as expected :)

**Closed by SMadani** 2022-10-23 12:41 UTC
Labels: enhancement
